"""add lang to genres

Revision ID: cb703f640bd3
Revises: 28c8bc46928d
Create Date: 2026-01-21 20:56:19.497732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb703f640bd3'
down_revision: Union[str, Sequence[str], None] = '28c8bc46928d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('lang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'lang')
    # ### end Alembic commands ###
